# Generated by Django 4.1.3 on 2022-12-06 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0002_alter_item_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="claim_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="claim",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
